# Generated by Django 3.1.3 on 2020-11-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalEntry',
            fields=[
                ('storage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.storage')),
                ('posted', models.BooleanField(default=False, verbose_name='Проведен')),
                ('document_type', models.PositiveSmallIntegerField(choices=[('document', 0), ('cancel', 1)], default=0, verbose_name='Тип')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('storage.storage',),
        ),
    ]
