# Generated by Django 3.1.3 on 2020-11-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0003_expectedarrival_expectedarrivalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='arrivalentry',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrivals.arrival', verbose_name='Приемка'),
        ),
    ]
