# Generated by Django 3.1.3 on 2020-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0006_auto_20201120_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedarrival',
            name='kis_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expectedarrival',
            name='kis_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
