# Generated by Django 3.1.3 on 2020-11-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0007_auto_20201120_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expectedarrival',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
