# Generated by Django 3.1.3 on 2020-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0009_arrival_expected_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Поступление товаров'), (1, 'Возврат поставщику'), (2, 'Возврат от покупателя'), (3, 'Внутренее перемещение')], default=0),
        ),
        migrations.AlterField(
            model_name='arrivalentry',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Документ'), (1, 'Отмена')], default=0, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='expectedarrival',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expectedarrival',
            name='kis_date',
            field=models.DateTimeField(null=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='expectedarrival',
            name='kis_number',
            field=models.CharField(max_length=64, null=True, verbose_name='Номер заявки'),
        ),
        migrations.AlterField(
            model_name='expectedarrival',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Поступление товаров'), (1, 'Возврат поставщику'), (2, 'Возврат от покупателя'), (3, 'Внутренее перемещение')], default=0),
        ),
    ]
