# Generated by Django 3.1.3 on 2020-11-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arrivals', '0010_auto_20201128_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedarrivalentry',
            name='expected_arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='arrivals.expectedarrival', verbose_name='Ожидаемая Приемка'),
        ),
    ]
