# Generated by Django 3.1.3 on 2020-11-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('type', models.PositiveSmallIntegerField(choices=[('Поставщик', 0), ('Покупатель', 1)], default=0)),
            ],
        ),
    ]
